animal_traits_ja = {
    "フクロウ": {"体型": "小柄で丸みのある体", "脚": "鋭い爪", "特徴": "神秘的で知的", "肌": "ふわふわの羽毛", "動き": "滑空する", "環境": "夜の森"},
    "トラ": {"体型": "しなやかな筋肉質", "脚": "力強い脚", "特徴": "俊敏で優雅", "肌": "短い毛", "動き": "静かに歩く", "環境": "ジャングル"},
    "イルカ": {"体型": "流線型", "脚": "ヒレ", "特徴": "知的で社交的", "肌": "滑らか", "動き": "水中で泳ぐ", "環境": "海"},
    "ハチドリ": {"体型": "小さく軽やか", "脚": "小さい足", "特徴": "華やかで活発", "肌": "虹色の羽毛", "動き": "空中で静止", "環境": "花のある場所"},
    "ブタ": {"体型": "丸い体", "脚": "短い脚", "特徴": "好奇心旺盛", "肌": "ピンクで柔らかい", "動き": "のんびり歩く", "環境": "牧場"},
    "ニワトリ": {"体型": "小型", "脚": "細くて鋭い", "特徴": "警戒心が強い", "肌": "羽毛", "動き": "地面を跳ねる", "環境": "農場"},
    "牛": {"体型": "大型でがっしり", "脚": "太く安定", "特徴": "穏やか", "肌": "短毛", "動き": "ゆっくり歩く", "環境": "牧草地"},
    "ワニ": {"体型": "細長く筋肉質", "脚": "低い足", "特徴": "冷静な捕食者", "肌": "硬い鱗", "動き": "這う", "環境": "川辺"},
    "クマ": {"体型": "大きく強い", "脚": "太い脚", "特徴": "力強いが愛嬌", "肌": "厚い毛", "動き": "ゆっくり歩く", "環境": "森林"},
    "キリン": {"体型": "首が長い", "脚": "長い足", "特徴": "高い視野", "肌": "短毛と模様", "動き": "優雅に歩く", "環境": "サバンナ"},
    "ペンギン": {"体型": "丸い胴体", "脚": "短くて平たい足", "特徴": "愛らしく氷上を滑る", "肌": "なめらかで光沢のある羽毛", "動き": "滑るように移動", "環境": "極地"},
    "カメレオン": {"体型": "細身で柔軟", "脚": "指が分かれた足", "特徴": "色が変化する", "肌": "ざらついた鱗", "動き": "ゆっくり移動", "環境": "熱帯林"},
    "サル": {"体型": "機敏で小型", "脚": "手足のような四肢", "特徴": "賢くて好奇心旺盛", "肌": "柔らかい毛", "動き": "木登りやジャンプ", "環境": "ジャングル"},
    "タコ": {"体型": "柔らかく丸い", "脚": "8本の吸盤付き腕", "特徴": "変幻自在", "肌": "ぬめりのある肌", "動き": "水中を自在に移動", "環境": "海中"},
    "カバ": {"体型": "巨大で重量感のある体", "脚": "短く太い脚", "特徴": "穏やかだが力強い", "肌": "灰色で厚い皮膚", "動き": "水中を歩く", "環境": "川辺"},
    "カエル": {"体型": "小型でぴょんぴょん跳ねる体", "脚": "長く強い後脚", "特徴": "ぬめりのある皮膚", "肌": "滑らかでしっとり", "動き": "ジャンプする", "環境": "湿地"},
    "パンダ": {"体型": "ずんぐりむっくり", "脚": "短くて太い脚", "特徴": "のんびりしてかわいい", "肌": "白黒のふわふわの毛", "動き": "ゆっくり動く", "環境": "竹林"},
    "ワシ": {"体型": "がっしりとした体", "脚": "鋭い爪の足", "特徴": "空を滑空する狩人", "肌": "羽毛に覆われた体", "動き": "高く飛び滑空", "環境": "山岳地帯"},
    "フラミンゴ": {"体型": "細長く優雅な体", "脚": "非常に長い脚", "特徴": "ピンク色で群れる鳥", "肌": "なめらかな羽毛", "動き": "水辺で片足立ち", "環境": "湿地や湖畔"},
    "クジャク": {"体型": "中型で扇状の尾羽を持つ", "脚": "鋭い爪の足", "特徴": "華やかな尾を持つ", "肌": "鮮やかな羽毛", "動き": "尾羽を広げて歩く", "環境": "森の縁や平地"}
    "ネコ": {"体型": "しなやかで小柄な体", "脚": "柔らかく鋭い爪の足", "特徴": "気まぐれで素早い", "肌": "短毛でなめらか", "動き": "静かに歩き、素早く跳ねる", "環境": "家屋や都市、森"},
    "シカ": {"体型": "細身で足の長い体", "脚": "速く走れる四肢", "特徴": "警戒心が強く俊敏", "肌": "短い毛皮", "動き": "跳ねるように走る", "環境": "森林や草原"},
    "イヌ": {"体型": "筋肉質で中型の体", "脚": "頑丈な足", "特徴": "忠実で活発", "肌": "短毛または長毛", "動き": "走るのが得意", "環境": "家庭や野外"},
    "ツル": {"体型": "背が高く細い体", "脚": "長い脚", "特徴": "優雅で静か", "肌": "白くてなめらかな羽毛", "動き": "水辺をゆっくり歩く", "環境": "湿地や湖畔"},
    "シマウマ": {"体型": "がっしりとした草食動物の体", "脚": "速く走れる四肢", "特徴": "縞模様で群れる性質", "肌": "白黒の短毛", "動き": "草原を駆ける", "環境": "アフリカのサバンナ"},
    "カモノハシ": {"体型": "平たいくちばしと低い体", "脚": "水かきのついた足", "特徴": "水陸両生で珍しい外見", "肌": "短くて柔らかい毛", "動き": "泳いだり這うように歩く", "環境": "川辺や湿地"},
    "ハシビロコウ": {"体型": "大きくがっしりとした体", "脚": "太く長い脚", "特徴": "動かず静かに獲物を狙う", "肌": "灰色の羽毛", "動き": "ゆっくりと慎重に動く", "環境": "湿地帯"},
    "ゴリラ": {"体型": "大型で筋肉質な体", "脚": "太くて力強い腕と足", "特徴": "群れで生活し穏やか", "肌": "黒く短い毛", "動き": "ナックルウォークで歩く", "環境": "熱帯雨林"},
    "ゾウ": {"体型": "非常に大きな体", "脚": "太くて柱のような脚", "特徴": "知能が高く温厚", "肌": "厚くしわのある肌", "動き": "ゆっくりと大地を踏みしめる", "環境": "草原や森林"},
    "ウサギ": {"体型": "小柄で丸みを帯びた体", "脚": "強くて跳ねる後ろ脚", "特徴": "臆病で素早い", "肌": "ふわふわの毛", "動き": "跳ねるように走る", "環境": "草原や林"},
    "キツネ": {"体型": "スリムでしなやかな体", "脚": "素早く走れる足", "特徴": "狡猾で好奇心旺盛", "肌": "赤褐色の柔らかな毛", "動き": "静かに歩きすばやく動く", "環境": "森や山野"},
    "タヌキ": {"体型": "丸っこく柔らかな体", "脚": "短く太い足", "特徴": "のんびりで人懐っこい", "肌": "ふさふさの毛", "動き": "ちょこちょこと歩く", "環境": "里山や農村"},
    "ヒツジ": {"体型": "ふっくらとした体", "脚": "しっかりとした四肢", "特徴": "おだやかで集団行動する", "肌": "もこもこの羊毛", "動き": "のんびり歩く", "環境": "牧草地や丘陵地"}
}

animal_traits_en = {
    "フクロウ": {"name": "owl", "body": "compact and rounded", "limbs": "sharp talons", "vibe": "mysterious and intelligent", "texture": "fluffy feathers", "movement": "gliding silently", "habitat": "nocturnal forests"},
    "トラ": {"name": "tiger", "body": "sleek and muscular", "limbs": "powerful legs", "vibe": "agile and graceful", "texture": "short fur", "movement": "moving silently", "habitat": "jungles"},
    "イルカ": {"name": "dolphin", "body": "streamlined", "limbs": "fins", "vibe": "intelligent and social", "texture": "smooth skin", "movement": "swimming fast", "habitat": "ocean"},
    "ハチドリ": {"name": "hummingbird", "body": "tiny and light", "limbs": "small feet", "vibe": "vivid and energetic", "texture": "iridescent feathers", "movement": "hovering mid-air", "habitat": "flower meadows"},
    "ブタ": {"name": "pig", "body": "round", "limbs": "short legs", "vibe": "curious and friendly", "texture": "pink soft skin", "movement": "plodding", "habitat": "farms"},
    "ニワトリ": {"name": "chicken", "body": "small", "limbs": "thin legs", "vibe": "alert and twitchy", "texture": "feathered", "movement": "hopping", "habitat": "barnyards"},
    "牛": {"name": "cow", "body": "heavy and solid", "limbs": "sturdy legs", "vibe": "gentle and calm", "texture": "short fur", "movement": "slowly walking", "habitat": "fields"},
    "ワニ": {"name": "crocodile", "body": "elongated and strong", "limbs": "low squat legs", "vibe": "calm and deadly", "texture": "rough scales", "movement": "crawling", "habitat": "riverbanks"},
    "クマ": {"name": "bear", "body": "large and strong", "limbs": "thick legs", "vibe": "strong but gentle", "texture": "thick fur", "movement": "slow walking", "habitat": "forests"},
    "キリン": {"name": "giraffe", "body": "tall with long neck", "limbs": "long legs", "vibe": "gentle and observant", "texture": "spotted short fur", "movement": "gracefully walking", "habitat": "savannas"},
    "ペンギン": {"name": "penguin", "body": "rounded torso", "limbs": "short flat feet", "vibe": "cute and waddling", "texture": "glossy feathers", "movement": "sliding on ice", "habitat": "polar regions"},
    "カメレオン": {"name": "chameleon", "body": "slim and flexible", "limbs": "split-fingered limbs", "vibe": "color-shifting", "texture": "rough scales", "movement": "slowly crawling", "habitat": "tropical forests"},
    "サル": {"name": "monkey", "body": "agile and small", "limbs": "gripping limbs", "vibe": "clever and curious", "texture": "soft fur", "movement": "climbing and jumping", "habitat": "jungles"},
    "タコ": {"name": "octopus", "body": "soft and round", "limbs": "eight suctioned arms", "vibe": "morphing and elusive", "texture": "slippery skin", "movement": "floating underwater", "habitat": "ocean"},
    "カバ": {"name": "hippopotamus", "body": "massive and heavy", "limbs": "short thick legs", "vibe": "gentle yet strong", "texture": "gray thick skin", "movement": "walking underwater", "habitat": "riverside"},
    "カエル": {"name": "frog", "body": "small and springy", "limbs": "long jumping legs", "vibe": "moist and reactive", "texture": "smooth", "movement": "jumping", "habitat": "wetlands"},
    "パンダ": {"name": "panda", "body": "plump", "limbs": "short and thick legs", "vibe": "gentle and cute", "texture": "black and white fur", "movement": "slow moving", "habitat": "bamboo forest"},
    "ワシ": {"name": "eagle", "body": "powerful", "limbs": "taloned feet", "vibe": "soaring hunter", "texture": "feathered", "movement": "gliding", "habitat": "mountains"},
    "フラミンゴ": {"name": "flamingo", "body": "slender and elegant", "limbs": "long legs", "vibe": "pink and graceful", "texture": "smooth feathers", "movement": "standing on one leg", "habitat": "wetlands and lakes"},
    "クジャク": {"name": "peacock", "body": "medium and decorated", "limbs": "clawed feet", "vibe": "flamboyant", "texture": "vivid plumage", "movement": "strutting and displaying", "habitat": "open forest and grassland"}
    "ネコ": {"name": "Cat", "body": "slender and small", "limbs": "soft feet with sharp claws", "vibe": "whimsical and agile", "texture": "short smooth fur", "movement": "silent and quick", "habitat": "homes, cities, forests"},
    "シカ": {"name": "Deer", "body": "lean with long legs", "limbs": "swift-running legs", "vibe": "alert and graceful", "texture": "short fur", "movement": "bounding stride", "habitat": "forests and meadows"},
    "イヌ": {"name": "Dog", "body": "muscular and medium-sized", "limbs": "strong legs", "vibe": "loyal and energetic", "texture": "short or long fur", "movement": "good runner", "habitat": "homes and outdoors"},
    "ツル": {"name": "Crane", "body": "tall and slender", "limbs": "long legs", "vibe": "elegant and calm", "texture": "smooth white feathers", "movement": "slowly walking in wetlands", "habitat": "lakes and marshes"},
    "シマウマ": {"name": "Zebra", "body": "robust herbivore build", "limbs": "fast-running legs", "vibe": "striped and social", "texture": "short black-and-white fur", "movement": "galloping across plains", "habitat": "African savanna"},
    "カモノハシ": {"name": "Platypus", "body": "flat-billed and low", "limbs": "webbed feet", "vibe": "amphibious and unique", "texture": "short soft fur", "movement": "swims and waddles", "habitat": "riversides and wetlands"},
    "ハシビロコウ": {"name": "Shoebill", "body": "large and bulky", "limbs": "thick long legs", "vibe": "still and focused predator", "texture": "gray feathers", "movement": "slow and precise", "habitat": "swamplands"},
    "ゴリラ": {"name": "Gorilla", "body": "large and muscular", "limbs": "powerful arms and legs", "vibe": "gentle and social", "texture": "short black hair", "movement": "knuckle-walking", "habitat": "tropical rainforests"},
    "ゾウ": {"name": "Elephant", "body": "very large and heavy", "limbs": "pillar-like legs", "vibe": "intelligent and calm", "texture": "thick wrinkled skin", "movement": "slow and steady", "habitat": "grasslands and forests"},
    "ウサギ": {"name": "Rabbit", "body": "small and round", "limbs": "strong hind legs", "vibe": "timid and fast", "texture": "fluffy fur", "movement": "hopping", "habitat": "fields and woods"},
    "キツネ": {"name": "Fox", "body": "slim and agile", "limbs": "swift legs", "vibe": "clever and curious", "texture": "soft reddish fur", "movement": "silent and quick", "habitat": "forests and hills"},
    "タヌキ": {"name": "Raccoon dog", "body": "round and soft", "limbs": "short sturdy legs", "vibe": "easygoing and sociable", "texture": "fluffy fur", "movement": "toddling", "habitat": "rural areas and woods"},
    "ヒツジ": {"name": "Sheep", "body": "plump and wooly", "limbs": "steady legs", "vibe": "gentle and flock-oriented", "texture": "thick wool", "movement": "calm walking", "habitat": "pastures and hills"}
}
